### ISSUE TITLE
Data Labels > Position - not saving after switch panels 

### ISSUE THREAD

**Issue by albertofilho82** [microsoft/powerbi-visuals-gantt#99] opened 2018-03-05 17:06 UTC
Configuration on Data Labels > Position - not saving after switch panels or close and open report.
It always brings position TOP as default.

![print](https://user-images.githubusercontent.com/37080912/36988774-6fb56e34-207e-11e8-8372-c69bf7f0debe.png)

**Comment by uve** [comment] 2018-03-06 06:52
@albertofilho82, I can't reproduce the issue.
Could you please record a screencast video to demonstrate this bug and paste it here?

**Comment by kabtoffe** [comment] 2018-05-10 16:43
I stumbled upon this too. In my case I use Group Tasks which makes the Position change to Top. Then I switch the setting to Right and all looks well until I switch to another report page and come back. I did some more testing at it seems like this only happens when Group Tasks is enabled. When it's off the setting is retained.

**Comment by helen508light** [comment] 2019-03-18 12:27
Hi, @albertofilho82 and @kabtoffe !
Thanks for your feedback. 
I managed to reproduce this bug, will add it to backlog

**Comment by helen508light** [comment] 2020-07-07 12:32
fixed in last versions

**Closed by helen508light** 2020-07-07 12:32 UTC
Labels: bug
