### ISSUE TITLE
Problems with legend color in new update

### ISSUE THREAD

**Issue by imd93shk** [microsoft/powerbi-visuals-gantt#154] opened 2019-07-09 10:14 UTC
There seem to be an issue with the legend color in the new version. The black bars are either supposed to be red, green, blue or yellow but not black. 

Is there any way to revert back to old version of Gantt visuals? 

![Legend Color error](https://user-images.githubusercontent.com/25534360/60879761-f13b8480-a24a-11e9-940f-38bfb8548d7b.png)

**Comment by MrLock0107** [comment] 2019-07-09 11:53
Hi, we have the same problem...
![Cattura](https://user-images.githubusercontent.com/52703510/60885877-e552c100-a250-11e9-9573-c4b822bb2a87.PNG)

**Comment by MrLock0107** [comment] 2019-07-09 11:56
Hi, we have the same problem...i need teh documentation...thank's
![Cattura](https://user-images.githubusercontent.com/52703510/60886098-66aa5380-a251-11e9-9e31-4e18a06c09b6.PNG)

**Comment by uve** [comment] 2019-07-12 12:14
@imd93shk, @MrLock0107  can use share sample PBIX reports to see the issue?

**Comment by imd93shk** [comment] 2019-07-12 12:52
@uve Please the attached zip file containing .pbix and .xlsx file with a random chart.

More info on the problem is as shown in the figure below
![Error](https://user-images.githubusercontent.com/25534360/61129404-00296d80-a4bd-11e9-859e-c6bc1e86232e.PNG)


[Legend Color Error.zip](https://github.com/microsoft/powerbi-visuals-gantt/files/3386460/Legend.Color.Error.zip)

**Comment by MrLock0107** [comment] 2019-07-12 13:13
Sorry @uve , but i can't share the PBIX for company sensitive data...sorry

> @imd93shk, @MrLock0107 can use share sample PBIX reports to see the issue?

**Comment by MrLock0107** [comment] 2019-07-12 13:42
> @uve Si prega di trovare il file zip allegato contenente file .pbix e .xlsx con un grafico a caso.
> 
> Maggiori informazioni sul problema sono mostrate nella figura seguente
> 
> * Le linee rappresentano il colore richiesto (invece il nero o il verde)
>   ![Errore](https://user-images.githubusercontent.com/25534360/61129404-00296d80-a4bd-11e9-859e-c6bc1e86232e.PNG)
> 
> [Legend Color Error.zip](https://github.com/microsoft/powerbi-visuals-gantt/files/3386460/Legend.Color.Error.zip)

The problem is in the parentheses of the status task ... remove them

**Comment by imd93shk** [comment] 2019-07-12 13:54
@uve Thanks a lot. Now it works. Hope they document this or even better, correct this in the next update.

**Comment by helen508light** [comment] 2019-07-30 09:26
Has been fixed in release version

**Closed by helen508light** 2019-07-30 09:26 UTC
Labels: bug
